import sqlite3

conn = sqlite3.connect("language_notes.db")
c = conn.cursor()
c.execute("CREATE TABLE languages (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR)")
c.execute("CREATE TABLE words (id INTEGER PRIMARY KEY AUTOINCREMENT, language_id INTEGER, word VARCHAR, translation TEXT, speech_category INTEGER, gloss VARCHAR)")
c.execute("CREATE TABLE contexts (id INTEGER PRIMARY KEY AUTOINCREMENT, word_id INTEGER, context TEXT, source TEXT)")
c.execute("CREATE TABLE word_properties (word_id INTEGER, property_id INTEGER)")
c.execute("CREATE TABLE word_speech (word_id INTEGER, speech_id INTEGER)")
c.execute("CREATE TABLE properties (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR)")
c.execute("CREATE TABLE speech_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name VARCHAR)")
c.execute("CREATE TABLE replace (language_id INTEGER, to_replace VARCHAR, replace_with VARCHAR)")
c.execute("CREATE INDEX language_index ON languages(id)")
c.execute("CREATE INDEX word_index ON words(id)")
c.execute("CREATE INDEX context_index ON contexts(id)")
c.execute("CREATE INDEX property_index ON properties(id)")
c.execute("CREATE INDEX speech_index ON speech_categories(id)")
c.execute("CREATE INDEX language_name_index ON languages(name)")
c.execute("CREATE INDEX word_name_index ON words(word)")
c.execute("CREATE INDEX word_language_fk_index ON words(language_id)")
c.execute("CREATE INDEX context_word_fk_index ON contexts(word_id)")
c.execute("CREATE INDEX word_property_word_fk_index ON word_properties(word_id)")
c.execute("CREATE INDEX word_speech_word_fk_index ON word_speech(word_id)")
c.execute("CREATE INDEX word_property_property_fk_index ON word_properties(property_id)")
c.execute("CREATE INDEX word_speech_speech_fk_index ON word_speech(speech_id)")
c.execute("CREATE INDEX replace_index ON replace(language_id)")
conn.commit()
conn.close()
